# Generated by Django 3.2.13 on 2022-11-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_path', models.TextField()),
                ('movie_detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kobis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.TextField()),
                ('open_data', models.TextField()),
                ('average', models.FloatField()),
                ('sales', models.TextField()),
                ('sales_per', models.TextField()),
                ('sales_variation', models.TextField()),
                ('sales_total', models.TextField()),
                ('spectators', models.TextField()),
                ('spectators_variation', models.TextField()),
                ('spectators_total', models.TextField()),
                ('screen', models.TextField()),
                ('screen_time', models.TextField()),
                ('overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tmdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('vote_average', models.IntegerField()),
                ('vote_count', models.IntegerField()),
                ('release_date', models.DateField()),
                ('genre_ids', models.ManyToManyField(related_name='tmdbs', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.detail')),
            ],
        ),
    ]
